version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./api:/api
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - nginxphp

  php:
    build: .
    volumes:
      - ./api:/api
    expose:
      - 9000
    networks:
      - nginxphp

networks:
  nginxphp: